#!/bin/bash

up_xubuntu(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM}
}

up_ubuntu_ser(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM}
}

up_ubuntu_k8s(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_K8S}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_UBUNTU_K8S} ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_K8S}
}

up_win10(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_WIN10_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM}
}

down_xubuntu(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM} ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM}
}

down_ubuntu_ser(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM} ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM}
}

down_ubuntu_k8s(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_UBUNTU_K8S}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_K8S} ${DELL_SRC_SSD}${REL_PATH_UBUNTU_K8S}
}

down_win10(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_WIN10_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM} ${DELL_SRC_SSD}${REL_PATH_WIN10_VM}
}