#!/bin/bash

up_xubuntu(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM}
}

up_ubuntu_ser(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM}
}

up_k8s_master(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_MASTER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_K8S_MASTER_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_MASTER_VM}
}

up_k8s_node1(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_NODE1_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_K8S_NODE1_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_NODE1_VM}
}

up_win10(){
    mkdir ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${DELL_SRC_SSD}${REL_PATH_WIN10_VM} ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM}
}

down_xubuntu(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_XUBUNTU_VM} ${DELL_SRC_SSD}${REL_PATH_XUBUNTU_VM}
}

down_ubuntu_ser(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_UBUNTU_SER_VM} ${DELL_SRC_SSD}${REL_PATH_UBUNTU_SER_VM}
}

down_k8s_master(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_K8S_MASTER_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_MASTER_VM} ${DELL_SRC_SSD}${REL_PATH_K8S_MASTER_VM}
}

down_k8s_node1(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_K8S_NODE1_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_K8S_NODE1_VM} ${DELL_SRC_SSD}${REL_PATH_K8S_NODE1_VM}
}

down_win10(){
    mkdir ${DELL_SRC_SSD}${REL_PATH_WIN10_VM}
    cp --exclude=${LOGS_DIR} --log-file=${LOG_PATH_DELL} --recursive ${MNT_POINT_EXT_DRIVE}${REL_PATH_WIN10_VM} ${DELL_SRC_SSD}${REL_PATH_WIN10_VM}
}