#!/bin/bash

src_dir="$(realpath $(dirname $0))/src"

cp -fv  "${src_dir}/.bashrc" ~/.bashrc
cp -fv "${src_dir}/.bash_aliases" ~/.bash_aliases
cp -fv "${src_dir}/.git_aliases" ~/.git_aliases
cp -fv "${src_dir}/.docker_aliases" ~/.docker_aliases

mkdir -p ~/scripts
cp -fv "${src_dir}/scripts/git-completion.bash" ~/scripts/git-completion.bash
cp -fv "${src_dir}/scripts/git-prompt.sh" ~/scripts/git-prompt.sh

if [ "$(command -v kind)" ]; then
    mkdir -p ~/.bash-completion
    cp -fv "${src_dir}/.bash-completion/kind-completion" ~/.bash-completion/kind-completion
fi