#!/bin/bash

script="$(realpath $(dirname $0))/core/prepare_fs"
source "$script"

root_dir_app_git="${ROOT_DIR_WORK_ENV}/applications/PortableGit"

if [ ! -d "$root_dir_git" ]; then
    echo -e "Directory ${root_dir_app_git} doesn't exist"
    exit 2
fi

dest="${ROOT_DIR_BACKUP_CFG}/git_win_cfg"

log_dir="${LOGS_DIR}/backup_win_git_cfg"
log_file="${log_dir}/$(date '+%d.%m.%Y_%H-%M-%S').log"

mkdir --parents "$dest" "$log_dir"

rsync --recursive --perms  --times --group --owner --specials --human-readable \
--stats --progress --del --verbose --out-format="%t %f %b" --log-file="$log_file" \
--exclude=.python_history --exclude=.cache \
--exclude=.git --exclude=.gitignore --exclude=README.md --exclude=.cache \
"${root_dir_app_git}/home" "${root_dir_app_git}/etc/profile" "$dest"